language: node_js

node_js:
- '5.9.1'

sudo: required

before_install:
- sudo wget http://security.ubuntu.com/ubuntu/pool/main/i/icu/libicu52_52.1-3ubuntu0.4_amd64.deb
- sudo dpkg -i libicu52_52.1-3ubuntu0.4_amd64.deb
- npm install --quiet -g gulp jspm
- jspm config registries.github.remote https://github.jspm.io
- jspm config registries.github.auth YjA5MTprcnRnbWszYQ==
- jspm config registries.github.maxRepoSize 0
- jspm config registries.github.handler jspm-github

#before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- nohup bash -c "./node_modules/protractor/bin/webdriver-manager start 2>&1 &"
- sleep 3

script:
- gulp compile
- gulp test:unit

cache:
  directories:
  - ./node_modules
  - ./vendor
  - $HOME/.nvm
